# Generated by Django 3.1.13 on 2022-12-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_medic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('status_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='business_owner',
            name='location',
        ),
        migrations.AddField(
            model_name='business_owner',
            name='business_type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='business_owner',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='business_owner',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='business_owner',
            name='latitude',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='business_owner',
            name='longitude',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='business_owner',
            name='sector',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Request_service',
            fields=[
                ('services_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('service_type', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('request_sender', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(default='0', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='car_medic.status')),
            ],
        ),
    ]
