# Generated by Django 3.1.13 on 2022-12-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_medic', '0002_auto_20221208_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
    ]
